version: "3.7"

services:

  svnadmin:
    container_name: svnadmin
    image: elleflorio/svn-server:latest
    ports:
      - "80:80"
      - "3690:3690"
    environment:
      SET_PERMS: "false"
    volumes:
      - ${PWD}/svnadmin/.data:/home/svnedge/csvn/data
