version: "3.7"

services:

  svn-server:
    container_name: svn-server
    image: elleflorio/svn-server:latest
    ports:
      - "80:80"
      - "3690:3690"
    environment:
      SET_PERMS: "false"
    volumes:
      - ${PWD}/svn-server/.data:/home/svn
